titanic/titanic/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("titanicapp.urls"))
]

from django.conf import settings
from django.conf.urls.static import static

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

titanic/titanicapp/urls.py
from django.urls import path
from .views import home, answer, about

app_name = 'titanicapp'
urlpatterns = [
	path('', home, name="home"),
	path('answer/', answer, name="answer"),
	path('about-us/', about, name="about-us"),
]

titanic/titanicapp/models.py
from django.db import models

class person(models.Model):
	CHOICES = (('Male', "Male"),('Female', "Female"))
	name = models.CharField(max_length=100, null=True)
	sex = models.CharField(max_length=10, choices=CHOICES)
	age = models.IntegerField()

	def __str__(self):
		return self.name

titanic/titanicapp/forms.py
from django import forms

class PersonForm(forms.Form):
	CHOICES = (('Male', "Male"),('Female', "Female"))
	name = forms.CharField(
		label="your name",
		max_length=100,
		widget=forms.TextInput(attrs={'class': 'text-dark fr form-control mx-3 animate__animated animate__fadeInUp'})
	)
	age = forms.IntegerField(
		label="your age",
		widget=forms.NumberInput(attrs={'class': 'text-dark fr form-control mx-3 animate__animated animate__fadeInUp'})
	)
	sex = forms.ChoiceField(
		label="your sex",
		choices=CHOICES,
		widget=forms.Select(attrs={'class': 'text-dark fr form-control mx-3 animate__animated animate__fadeInUp'})
	)

titanic/titanicapp/views.py
from django.views.generic import CreateView
from .forms import PersonForm
from django.shortcuts import render, redirect
from django.http import HttpResponse
from extentions.ml_titan import ml

def home(request):
    if request.method == 'POST':
        form = PersonForm(request.POST)

        if form.is_valid():
            return form.save()

    else:
        form = PersonForm()

    return render(request, 'home.html', {'form': form,})

def answer(request):
	age = request.POST['age']
	sex = request.POST['sex']
	context = {
		'name' : request.POST['name'],
		'age' : age,
		'sex' : sex,
		'ad' : ml(age, sex),
	}
	return render(request, 'answer.html', context)

def about(request):
	return render(request, 'about.html')

titanic/templates/about.html
{% extends 'base.html' %}
{% load static %}
{% block main %}
<section id="intro">
	<div class="intro-container">
	  <div id="introCarousel" class="carousel slide carousel-fade" data-ride="carousel">
        <div class="carousel-inner" role="listbox">
        	<div class="carousel-item active" style="background-image: url({% static 'assets/img/about-us.jpg' %})">
        	<div class="carousel-container">
            <div class="container row">
            	<h2 class="col-md-12 text-center" style="color: #ff7900;">Titanic</h2>
            	<h3 class="col-md-12 text-center text-light">Created By Parsa & Daniyal</h2>

            	<div class="col-md-6 my-3 text-center">
	      			  <p class="h5"><b>Contact Parsa</b></p>
	      			  <p><i><i class="fa fa-envelope" aria-hidden="true"></i> parsabiglarykord5892@gmail.com</i></p>
	      		    <p><a href="https://github.com/parsa5892"><i class="fa fa-github"></i> Parsa Github</a></p>
	      		  </div>
	      		  <div class="col-md-6 my-3 text-center">
	      			  <p class="h5"><b>Contact Daniyal</b></p>
	      			  <p><i><i class="fa fa-envelope" aria-hidden="true"></i> gcmstr@gmail.com</i></p>
	      		  	<p><a href="https://github.com/mstrgc"><i class="fa fa-github"></i> Daniyal Github</a></p>
	      		  </div>
	    			</div>
	  			</div>
				</div>
			</div>
		</div>
	</div>
</section>
{% endblock %}

titanic/templates/answer.html
{% extends 'base.html' %}
{% load static %}
{% block main %}
<section id="intro">
	<div class="intro-container">
	  <div id="introCarousel" class="carousel slide carousel-fade" data-ride="carousel">
      <div class="carousel-inner" role="listbox">
        <div class="carousel-item active" style="background-image: url({% static 'assets/img/home.jpg' %})">
        	<div class="carousel-container">
            <div class="container">
            	<h3 class="text-center text-danger animate__animated animate__fadeInUp"><b>Will you die or will you survive?</b></h3>
	      			<p class="my-2 animate__animated animate__fadeInUp">Your name is {{name}}</p>
	      			<p class="my-2 animate__animated animate__fadeInUp">and</p>
	      			<p class="my-2 animate__animated animate__fadeInUp">You are {{age}} years old</p>
	      			<p class="my-2 animate__animated animate__fadeInUp">and</p>
	      			<p class="my-2 animate__animated animate__fadeInUp">You are a {% if sex == 'Male' %}man{% else %}woman{% endif %}</p>
	      			<br>
	      			<p class="orange animate__animated animate__fadeInUp"><i>If you were on the Titanic you would be ...</i></p>
	      			{% if ad == 'a' %}
	      			<h4 class="text-center text-success animate__animated animate__fadeInUp"><b>fortunatly you survive</b></h4>
	      			{% elif ad == 'd' %}
	      			<h4 class="text-center text-danger animate__animated animate__fadeInUp"><b>unfortunatly you die</b></h4>
	      			{% elif ad == 'f' %}
	      			<h4 class="text-center text-warning animate__animated animate__fadeInUp"><b>it's fifty fifty</b></h4>
	      			{% endif %}
	    			</div>
	  			</div>
				</div>
			</div>
		</div>
	</div>
</section>
{% endblock %}

titanic/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">
  <title>Titanic</title>
  <meta content="" name="description">
  <meta content="" name="keywords">
   <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,700,700i|Montserrat:300,400,500,700" rel="stylesheet">
  <!-- Vendor CSS Files -->
  <link href="{% static 'assets/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/animate.css/animate.min.css' %}" rel="stylesheet">
  <!-- Template Main CSS File -->
  <link href="{% static 'assets/css/style.css' %}" rel="stylesheet">
  <!-- =======================================================
  * Template Name: BizPage - v3.1.1
  * Template URL: https://bootstrapmade.com/bizpage-bootstrap-business-template/
  * Author: BootstrapMade.com
  * License: https://bootstrapmade.com/license/
  ======================================================== -->
</head>
<body>
  <!-- ======= Header ======= -->
  <header id="header" class="fixed-top header-transparent">
    <div class="container-fluid">
      <div class="row justify-content-center">
        <div class="col-lg-11 d-flex align-items-center">
          <h1 class="logo mr-auto"><a href="{% url 'titanicapp:home' %}">Titanic</a></h1>
          <nav class="nav-menu d-none d-lg-block">
            <ul>
              <li class="active"><a href="{% url 'titanicapp:home' %}">Home</a></li>
              <li><a href="{% url 'titanicapp:about-us' %}">About Us</a></li>
            </ul>
          </nav><!-- .nav-menu -->
        </div>
      </div>
    </div>
  </header><!-- End Header -->
  <!-- block main-->
  {% block main %}{% endblock %}
  <!-- end block-->
  <!-- ======= Footer ======= -->
  <footer id="footer">
    <div class="container">
      <div class="copyright">
        <strong>Titanic</strong>
      </div>
      <div class="credits">
        Created by <a href="{% url 'titanicapp:about-us' %}">Parsa & Daniyal</a>
      </div>
    </div>
  </footer>
  <!-- End Footer -->
  <!-- Vendor JS Files -->
  <script src="{% static 'assets/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
  <!-- Template Main JS File -->
  <script src="{% static 'assets/js/main.js' %}"></script>
</body>
</html>

titanic/templates/home.html
{% extends 'base.html' %}
{% load static %}
{% block main %}
<section id="intro">
<div class="intro-container">
  <div id="introCarousel" class="carousel slide carousel-fade" data-ride="carousel">
    <div class="carousel-inner" role="listbox">
      <div class="carousel-item active" style="background-image: url({% static 'assets/img/home.jpg' %})">
        <div class="carousel-container">
          <div class="container row">
            <div class="col-md-6 text-left">
              <h1 class="orange d-block float-left animate__animated animate__fadeInUp">Titanic</h1>
              <br>
              <br>
              <br>
              <p class="h4 animate__animated animate__fadeInUp">You are one of the passengers of the Titanic.</p>
              <p class="text-danger h4 animate__animated animate__fadeInUp"><i>Will you die or will you survive?</i></p>
              <p class="h4 animate__animated animate__fadeInUp">Try it!</p>
            </div>
            <div class="col-md-6">
              <form method="post" action="{% url 'titanicapp:answer' %}">
                {% csrf_token %}
                <label class="orange h5 text-light float-left my-3 mx-3 animate__animated animate__fadeInUp">{{form.name.label}}</label>
                {{form.name}}
                <label class="orange h5 text-light float-left my-3 mx-3 animate__animated animate__fadeInUp">{{form.age.label}}</label>
                {{form.age}}
                <label class="orange h5 text-light float-left my-3 mx-3 animate__animated animate__fadeInUp">{{form.sex.label}}</label>
                {{form.sex}}
                <button type="submit" class="scrollto animate__animated animate__fadeInU border-0 my-5 btn-get-started">Start Machine</button>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
</section>
{% endblock %}

titanic/templates/index.html
{% load static %}
{% load widget_tweaks %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title>Titanic</title>
  <meta content="" name="description">
  <meta content="" name="keywords">

   <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,700,700i|Montserrat:300,400,500,700" rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link href="{% static 'assets/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/icofont/icofont.min.css" rel="stylesheet' %}">
  <link href="{% static 'assets/vendor/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/ionicons/css/ionicons.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/animate.css/animate.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/venobox/venobox.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/owl.carousel/assets/owl.carousel.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/aos/aos.css' %}" rel="stylesheet">

  <!-- Template Main CSS File -->
  <link href="{% static 'assets/css/style.css' %}" rel="stylesheet">

  <!-- =======================================================
  * Template Name: BizPage - v3.1.1
  * Template URL: https://bootstrapmade.com/bizpage-bootstrap-business-template/
  * Author: BootstrapMade.com
  * License: https://bootstrapmade.com/license/
  ======================================================== -->
</head>

<body>

  <!-- ======= Header ======= -->
  <header id="header" class="fixed-top header-transparent">
    <div class="container-fluid">

      <div class="row justify-content-center">
        <div class="col-lg-11 d-flex align-items-center">
          <h1 class="logo mr-auto"><a href="index.html">Titanic</a></h1>
          <!-- Uncomment below if you prefer to use an image logo -->
          <!-- <a href="index.html" class="logo mr-auto"><img src="assets/img/logo.png" alt="" class="img-fluid"></a>-->

          <nav class="nav-menu d-none d-lg-block">
            <ul>
              <li class="active"><a href="{% url 'titanicapp:home' %}">Home</a></li>
              <li><a href="#about">About Us</a></li>
            </ul>
          </nav><!-- .nav-menu -->
        </div>
      </div>

    </div>
  </header><!-- End Header -->

  <!-- ======= Intro Section ======= -->
  <section id="intro">
    <div class="intro-container">
      <div id="introCarousel" class="carousel slide carousel-fade" data-ride="carousel">

        <ol class="carousel-indicators"></ol>

        <div class="carousel-inner" role="listbox">

          <div class="carousel-item active" style="background-image: url({% static 'assets/img/intro-carousel/1.jpg' %})">
            <div class="carousel-container">
              <div class="container row">
                <div class="col-md-6 text-left">
                  <h1 class="d-block logo float-left animate__animated animate__fadeInUp"><a href="index.html">Titanic</a></h1>
                  <br>
                  <br>
                  <br>
                  <p class="h4 animate__animated animate__fadeInUp">You are one of the passengers of the Titanic.</p>
                  <p class="text-danger h4 animate__animated animate__fadeInUp">Will you die or will you survive?</p>
                  <p class="h4 animate__animated animate__fadeInUp">Try it!</p>
                </div>
                <div class="col-md-6">
                  <form>
                    {% csrf_token %}
                    <label class="h5 text-light float-left my-3 mx-3 animate__animated animate__fadeInUp">{{form.name.label}}</label>
                    {{form.name|add_class:"form-control mx-3 animate__animated animate__fadeInUp"}}
                    <label class="h5 text-light float-left my-3 mx-3 animate__animated animate__fadeInUp">{{form.age.label}}</label>
                    {{form.age|add_class:"form-control mx-3 animate__animated animate__fadeInUp"}}
                    <label class="h5 text-light float-left my-3 mx-3 animate__animated animate__fadeInUp">{{form.sex.label}}</label>
                    {{form.sex|add_class:"form-control mx-3 animate__animated animate__fadeInUp"}}
                    <a href="#featured-services" class="mt-4 btn-get-started scrollto animate__animated animate__fadeInUp">Start Machine</a>
                  </form>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section><!-- End Intro Section -->

  <main id="main">
</body>
</html